#!/usr/bin/env bash
set -e

VERSION=2.54
SHA_256="CC3EE6ED A0B4BC46 DB378FD3 BBE6E2E5 F7480B4D 3AE544B7 F03330A3 45E838C2" # https://keepass.info/integrity.html

# Download application
ARCHIVE="KeePass-${VERSION}.zip"
LOCAL_ARCHIVE="/tmp/${ARCHIVE}"
if [[ ! -e "${LOCAL_ARCHIVE}" ]]; then (
  curl "https://downloads.sourceforge.net/project/keepass/KeePass%202.x/${VERSION}/${ARCHIVE}" \
    --location \
    --output "${LOCAL_ARCHIVE}" \
  ;
); fi

# Check integrity
SHA_256_FILE="${LOCAL_ARCHIVE}.sha256sum"
echo "${SHA_256// /} ${LOCAL_ARCHIVE}" > "${SHA_256_FILE}"
sha256sum --check "${SHA_256_FILE}" || exit 1

# Update application
APP_DIR="$(pwd)/app"
if [[ -e "${APP_DIR}" ]]; then (
  find "${APP_DIR}" ! -name "KeePass.config.xml" -type f -exec rm -f {} +
); fi
unzip "${LOCAL_ARCHIVE}" -d "${APP_DIR}"
sudo apt install -y mono-devel xdotool

# Create executable files
RUN_SCRIPT="run"
echo "#!/usr/bin/env bash" > "${RUN_SCRIPT}"
echo "mono \"${APP_DIR}/KeePass.exe\"" >> "${RUN_SCRIPT}"
chmod +x "${RUN_SCRIPT}"
AUTO_TYPE_SCRIPT="auto-type"
echo "#!/usr/bin/env bash" > "${AUTO_TYPE_SCRIPT}"
echo "flock --exclusive --nonblock /var/lock/KeePass_${AUTO_TYPE_SCRIPT}.lock \\" >> "${AUTO_TYPE_SCRIPT}"
echo "      --command \"mono \\\"${APP_DIR}/KeePass.exe\\\" --auto-type\"" >> "${AUTO_TYPE_SCRIPT}"
chmod +x "${AUTO_TYPE_SCRIPT}"

# Print steps to set up auto-type
echo "Add shortcut"
echo ""
echo "   1) Go to Settings - Keyboard"
echo "   2) Switch to Shortcuts tab"
echo "   3) Add Custom Shortcut for \"$(pwd)/${AUTO_TYPE_SCRIPT}\""
echo ""
read -p "[Press Any Key]"
